---

Resources:
  CodeBuildExcecutionPolicy:
    Type: AWS::IAM::Policy
   # Description: Setting IAM policy for service role for CodeBuild
    Properties:
      PolicyName: CodeBuildExcecutionPolicy
      PolicyDocument:
        Statement:
        - Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Effect: Allow
          Resource: '*'
        - Action:
          - s3:PutObject
          - s3:GetObject
          - s3:GetObjectVersion
          Effect: Allow
          Resource: '*'
        - Action:
          - codecommit:GitPull
          Effect: Allow
          Resource: '*'
        - Action:
          - kms:GenerateDataKey*
          - kms:Encrypt
          - kms:Decrypt
          Effect: Allow
          Resource: '*'      
      Roles:
      - !Ref CodeBuildExcecutionRole      
  CodeBuildExcecutionRole:
    Type: AWS::IAM::Role    
   # Description: Creating service role in IAM for AWS CodeBuild
    Properties:
      RoleName: CodeBuildExcecutionRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow          
          Principal:
            Service: 
            - codebuild.amazonaws.com
          Action: 
          - sts:AssumeRole
      Path: /
