---
service: ${self:custom.service}

provider: 
  name: aws
  stage: ${opt:env}
  region: us-east-1
  versionFunctions: false
  deploymentBucket:
    name: ${self:custom.bucket-deploymentself-name}
    serverSideEncryption: AES256
  

plugins:
  - serverless-pseudo-parameters
  - serverless-s3-remover
  - serverless-deployment-bucket

custom:
  ${file(parameters.yml)}

resources:
- ${file(codepipeline-policies-codebuild.yml)}
- ${file(codepipeline-policies-codepipeline.yml)}
- ${file(codepipeline-policies-out.yml)}
