---
service: ${self:custom.service}

provider: 
  name: aws
  stage: ${opt:env}
  region: us-east-1
  versionFunctions: false
  

plugins:
  - serverless-pseudo-parameters
  - serverless-s3-remover

custom:
  ${file(parameters.yml)}

resources:
- ${file(codepipeline-policies.yml)}
- ${file(codepipeline-policies-out.yml)}
