Resources:  
  EC2SampleDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: 
    - CodeDeployApplicationEC2
    Properties:
      ApplicationName:
        Ref: CodeDeployApplicationEC2
      Deployment:
        Description: "Deploy in EC2"
        IgnoreApplicationStopFailures: 'true'
        Revision:
          RevisionType: S3
          S3Location:
            Bucket: 
              Ref: ArtifactsBucket
            BundleType: Zip
            Key: ${self:custom.ec2-deployment.file}
      Ec2TagFilters:
        - Key: ${self:custom.ec2-deployment.tag-key}
          Value: ${self:custom.ec2-deployment.tag-value}
          Type: KEY_AND_VALUE
      ServiceRoleArn: 
        Fn::ImportValue: CodeDeployEC2ExcecutionRole       
