---

Resources:
  Webhook: 
    Type: 'AWS::CodePipeline::Webhook' 
    Properties:
      Name: ${self:custom.pipeline-webhook}
      AuthenticationConfiguration: 
        SecretToken: ${self:custom.github-aut-token}
      Filters: 
      - JsonPath: "$.ref" 
        MatchEquals: refs/heads/{Branch} 
      Authentication: GITHUB_HMAC 
      TargetPipeline: 
       Ref: Pipeline
      TargetAction: SourceAction
      TargetPipelineVersion: 
        Fn::GetAtt: [Pipeline,Version]
      RegisterWithThirdParty: 'true'