---
service: ${self:custom.service}

provider: 
  name: aws
  stage: ${opt:env}
  region: us-east-1
  versionFunctions: false

plugins:
  - serverless-pseudo-parameters
  - serverless-s3-remover

custom:
  ${file(parameters.yml)}

resources:
- ${file(pipeline-conditions.yml)}
- ${file(resources-parameters.yml)}
- ${file(pipeline-bucket.yml)}
- ${file(pipeline-codebuild.yml)}
# - ${file(pipeline-pipeline.yml)}

